---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: target-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: target-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.sdn.opsramp.com
  resources:
  - gatewaysubnets
  - gatewaysubnets/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: target-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: target-role
subjects:
- kind: ServiceAccount
  name: target-sa
  namespace: {{ .Release.Namespace }}
